version: '3.9'

services:
  react-app:
    container_name: react-vite-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
